// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlnvIyme4-HrLVwhUM23h4E4mEfWQO3jU',
    appId: '1:1051485347548:web:ab656bf6a925498ceb1e19',
    messagingSenderId: '1051485347548',
    projectId: 'auraquote-497106',
    authDomain: 'auraquote-497106.firebaseapp.com',
    storageBucket: 'auraquote-497106.firebasestorage.app',
    measurementId: 'G-S2GHC19RGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcVydDWr3txa2Cz92zJ345i4ytkFqLjsQ',
    appId: '1:1051485347548:android:63638173164d3a5deb1e19',
    messagingSenderId: '1051485347548',
    projectId: 'auraquote-497106',
    storageBucket: 'auraquote-497106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8bob5XZkkxqWydJrDjtG-N32_IyVEFN0',
    appId: '1:1051485347548:ios:977f31e946a0ac75eb1e19',
    messagingSenderId: '1051485347548',
    projectId: 'auraquote-497106',
    storageBucket: 'auraquote-497106.firebasestorage.app',
    androidClientId: '1051485347548-42uumum3hjoub7j58gtfof7mq6c7jg4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.auraQuote',
  );
}
